import type { Metadata } from "next";
import "./globals.scss";
import Tailwind from "primereact/passthrough/tailwind";
import { PrimeReactProvider } from "primereact/api";
import { NextAuthProvider } from "./providersAuth";
import { Toaster } from "react-hot-toast";
import { Ripple } from "primereact/ripple";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const value = {
    ripple: true,
    pt: Tailwind,
  };
  return (
    <html lang="en">
      <body className="bg-slate-50 dark:bg-slate-950 dark:text-white">
        <div className="container mx-auto">
          <NextAuthProvider>
            <PrimeReactProvider value={value}>
              {children}
              <Toaster />
            </PrimeReactProvider>
          </NextAuthProvider>
        </div>
      </body>
    </html>
  );
}
