import type { Metadata } from "next";
import "./globals.scss";
import "./goodash.scss";
import Tailwind from "primereact/passthrough/tailwind";
import { PrimeReactProvider } from "primereact/api";
import { NextAuthProvider } from "./providersAuth";
import { Toaster } from "react-hot-toast";
// import { Ripple } from "primereact/ripple";
import { Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const value = {
    ripple: true,
    pt: Tailwind,
  };
  return (
    <html lang="en">
      <body
        id="body-layout"
        className={
          roboto.className +
          ` text-body-md relative font-sans font-normal text-gray-700 dark:text-gray-300 bg-surface-500 dark:bg-surfacedark-500 show`
        }
      >
        <NextAuthProvider>
          <PrimeReactProvider value={value}>
            {children}
            <Toaster />
          </PrimeReactProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
